train:
  tune:

    num_epochs : 50
    lr : 0.1

    vocab_size :
    max_len :
    input_dim :
    embed_dim : 512
    hidden_dim : 768
    num_heads : 12
    batch_size : 32
    dropout : 0.1
    layers : 12
    
