# Configuration for ParTUT dataset
dataset_name: partut

# Label mapping
label2id:
  ADJ: 0
  ADP: 1
  ADV: 2
  AUX: 3
  CCONJ: 4
  DET: 5
  INTJ: 6
  NOUN: 7
  NUM: 8
  PART: 9
  PRON: 10
  PROPN: 11
  PUNCT: 12
  SCONJ: 13
  SYM: 14
  VERB: 15
  X: 16
  _: 17

# Training parameters
training:
  learning_rates: [1e-5, 2e-5, 3e-5, 4e-5, 5e-5, 1e-4, 3e-4, 5e-4]
  batch_sizes: [16, 32]
  max_epochs: 30