# Configuration for GSD dataset
dataset_name: gsd

# Relation mapping
rel2id:
  _: 0
  acl: 1
  acl:relcl: 2
  advcl: 3
  advcl:cleft: 4
  advmod: 5
  amod: 6
  appos: 7
  aux: 8
  aux:caus: 9
  aux:pass: 10
  aux:tense: 11
  case: 12
  cc: 13
  ccomp: 14
  compound: 15
  conj: 16
  cop: 17
  csubj: 18
  csubj:pass: 19
  dep: 20
  dep:comp: 21
  det: 22
  discourse: 23
  dislocated: 24
  expl:comp: 25
  expl:pass: 26
  expl:pv: 27
  expl:subj: 28
  fixed: 29
  flat: 30
  flat:foreign: 31
  flat:name: 32
  goeswith: 33
  iobj: 34
  iobj:agent: 35
  mark: 36
  nmod: 37
  nsubj: 38
  nsubj:caus: 39
  nsubj:outer: 40
  nsubj:pass: 41
  nummod: 42
  obj: 43
  obj:agent: 44
  obj:lvc: 45
  obl: 46
  obl:agent: 47
  obl:arg: 48
  obl:mod: 49
  orphan: 50
  parataxis: 51
  parataxis:insert: 52
  punct: 53
  root: 54
  vocative: 55
  xcomp: 56

# Training parameters
training:
  learning_rates: [1.0e-5, 2.0e-5, 3.0e-5, 4.0e-5, 5.0e-5, 1.0e-4, 3.0e-4, 5.0e-4]
  batch_sizes: [16, 32]
  max_epochs: 30